# Generated by Django 4.2.5 on 2023-09-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='name',
            new_name='room_name',
        ),
    ]
