# Generated by Django 4.2.5 on 2023-09-26 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tictactoe', '0002_rename_name_gameroom_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='online',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
